export const EncabezadosMap = {
  transaccion: {
    numDocumentoIdObligado: "NUM DOCUMENTO ID OBLIGADO",
    numFactura: "NUMFACTURA",
    tipoNota: "TIPO NOTA",
    numNota: "NUM NOTA",
  },
  usuario: {
    tipoDocumentoIdentificacion: "TIPO DOCUMENTO IDENTIFICACION",
    numDocumentoIdentificacion: "NUM DOCUMENTO IDENTIFICACION",
    tipoUsuario: "TIPO USUARIO",
    fechaNacimiento: "FECHA NACIMIENTO",
    codSexo: "COD SEXO",
    codPaisResidencia: "COD PAIS RESIDENCIA",
    codMunicipioResidencia: "COD MUNICIPIO RESIDENCIA",
    codZonaTerritorialResidencia: "COD ZONA TERRITORIAL RESIDENCIA",
    incapacidad: "INCAPACIDAD",
    codPaisOrigen: "COD PAIS ORIGEN",
    consecutivo: "CONSECUTIVO",
  },
  consultas: {
    codPrestador: "COD PRESTADOR",
    fechaInicioAtencion: "FECHA INICIO ATENCION",
    numAutorizacion: "NUM AUTORIZACION",
    codConsulta: "COD CONSULTA",
    modalidadGrupoServicioTecSal: "MODALIDAD GRUPO SERVICIO TEC SAL",
    grupoServicios: "GRUPO SERVICIOS",
    codServicio: "COD SERVICIO",
    finalidadTecnologiaSalud: "FINALIDAD TECNOLOGIA SALUD",
    causaMotivoAtencion: "CAUSA MOTIVO ATENCION",
    codDiagnosticoPrincipal: "COD DIAGNOSTICO PRINCIPAL",
    codDiagnosticoRelacionado1: "COD DIAGNOSTICO RELACIONADO 1",
    codDiagnosticoRelacionado2: "COD DIAGNOSTICO RELACIONADO 2",
    codDiagnosticoRelacionado3: "COD DIAGNOSTICO RELACIONADO 3",
    tipoDiagnosticoPrincipal: "TIPO DIAGNOSTICO PRINCIPAL",
    tipoDocumentoIdentificacion: "TIPO DOCUMENTO IDENTIFICACION",
    numDocumentoIdentificacion: "NUM DOCUMENTO IDENTIFICACION",
    vrServicio: "VR SERVICIO",
    conceptoRecaudo: "CONCEPTO RECAUDO",
    valorPagoModerador: "VALOR PAGO MODERADOR",
    numFEVPagoModerador: "NUM FEV PAGO MODERADOR",
    consecutivo: "CONSECUTIVO",
  },

  procedimientos: {
    codPrestador: "COD PRESTADOR",
    fechaInicioAtencion: "FECHA INICIO ATENCION",
    idMIPRES: "ID MIPRES",
    numAutorizacion: "NUM AUTORIZACION",
    codProcedimiento: "COD PROCEDIMIENTO",
    viaIngresoServicioSalud: "VIA INGRESO SERVICIO SALUD",
    modalidadGrupoServicioTecSal: "MODALIDAD GRUPO SERVICIO TEC SAL",
    grupoServicios: "GRUPO SERVICIOS",
    codServicio: "COD SERVICIO",
    finalidadTecnologiaSalud: "FINALIDAD TECNOLOGIA SALUD",
    tipoDocumentoIdentificacion: "TIPO DOCUMENTO IDENTIFICACION",
    numDocumentoIdentificacion: "NUM DOCUMENTO IDENTIFICACION",
    codDiagnosticoPrincipal: "COD DIAGNOSTICO PRINCIPAL",
    codDiagnosticoRelacionado: "COD DIAGNOSTICO RELACIONADO",
    codComplicacion: "COD COMPLICACION",
    vrServicio: "VR SERVICIO",
    conceptoRecaudo: "CONCEPTO RECAUDO",
    valorPagoModerador: "VALOR PAGO MODERADOR",
    numFEVPagoModerador: "NUM FEV PAGO MODERADOR",
    consecutivo: "CONSECUTIVO",
  },

  hospitalizacion: {
    codPrestador: "COD PRESTADOR",
    viaIngresoServicioSalud: "VIA INGRESO SERVICIO SALUD",
    fechaInicioAtencion: "FECHA INICIO ATENCION",
    numAutorizacion: "NUM AUTORIZACION",
    causaMotivoAtencion: "CAUSA MOTIVO ATENCION",
    codDiagnosticoPrincipal: "COD DIAGNOSTICO PRINCIPAL",
    codDiagnosticoPrincipalE: "COD DIAGNOSTICO PRINCIPAL",
    codDiagnosticoRelacionadoE1: "COD DIAGNOSTICO RELACIONADO E1",
    codDiagnosticoRelacionadoE2: "COD DIAGNOSTICO RELACIONADO E2",
    codDiagnosticoRelacionadoE3: "COD DIAGNOSTICO RELACIONADO E3",
    codComplicacion: "COD COMPLICACION",
    condicionDestinoUsuarioEgreso: "CONDICION DESTINO USUARIO EGRESO",
    codDiagnosticoCausaMuerte: "COD DIAGNOSTICO CAUSA MUERTE",
    fechaEgreso: "FECHA EGRESO",
    consecutivo: "CONSECUTIVO",
  },

  medicamentos: {
    codPrestador: "COD PRESTADOR",
    numAutorizacion: "NUM AUTORIZACION",
    idMIPRES: "ID MIPRES",
    fechaDispensAdmon: "FECHA DISPENSADMON",
    codDiagnosticoPrincipal: "COD DIAGNOSTICO PRINCIPAL",
    codDiagnosticoRelacionado: "COD DIAGNOSTICO RELACIONADO",
    tipoMedicamento: "TIPO MEDICAMENTO",
    codTecnologiaSalud: "COD TECNOLOGIA SALUD",
    nomTecnologiaSalud: "NOM TECNOLOGIA SALUD",
    concentracionMedicamento: "CONCENTRACION MEDICAMENTO",
    unidadMedida: "UNIDAD MEDIDA",
    formaFarmaceutica: "FORMA FARMACEUTICA",
    unidadMinDispensa: "UNIDAD MIN DISPENSA",
    cantidadMedicamento: "CANTIDAD MEDICAMENTO",
    diasTratamiento: "DIAS TRATAMIENTO",
    tipoDocumentoIdentificacion: "TIPO DOCUMENTO IDENTIFICACION",
    numDocumentoIdentificacion: "NUM DOCUMENTO IDENTIFICACION",
    vrUnitMedicamento: "VR UNIT MEDICAMENTO",
    vrServicio: "VR SERVICIO",
    conceptoRecaudo: "CONCEPTO RECAUDO",
    valorPagoModerador: "VALOR PAGO MODERADOR",
    numFEVPagoModerador: "NUM FEV PAGO MODERADOR",
    consecutivo: "CONSECUTIVO",
  },

  otrosServicios: {
    codPrestador: "CODPRESTADOR",
    numAutorizacion: "NUMAUTORIZACION",
    idMIPRES: "IDMIPRES",
    fechaSuministroTecnologia: "FECHASUMINISTROTECNOLOGIA",
    tipoOS: "TIPOOS",
    codTecnologiaSalud: "CODTECNOLOGIASALUD",
    nomTecnologiaSalud: "NOMTECNOLOGIASALUD",
    cantidadOS: "CANTIDADOS",
    tipoDocumentoIdentificacion: "TIPODOCUMENTOIDENTIFICACION",
    numDocumentoIdentificacion: "NUMDOCUMENTOIDENTIFICACION",
    vrUnitOS: "VRUNITOS",
    vrServicio: "VRSERVICIO",
    conceptoRecaudo: "CONCEPTORECAUDO",
    valorPagoModerador: "VALORPAGOMODERADOR",
    numFEVPagoModerador: "NUMFEVPAGOMODERADOR",
    consecutivo: "CONSECUTIVO",
  },
};
